### ISSUE TITLE
Throwing ImportError: DLL load failed: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by bdsmgeek** [bebound/Pixiv#13]
`Traceback (most recent call last):
  File "D:\Dropbox\Documents\__Projects\Kinksters\Sprites\_tools\pixiv\pixiv.py", line 37, in <module>
    from api import PixivApi
  File "D:\Dropbox\Documents\__Projects\Kinksters\Sprites\_tools\pixiv\api.py", line 10, in <module>
    from AESCipher import AESCipher
  File "D:\Dropbox\Documents\__Projects\Kinksters\Sprites\_tools\pixiv\AESCipher.py", line 4, in <module>
    from Crypto import Random
  File "C:\Program Files\Python36\lib\site-packages\pycrypto-2.6.1-py3.6-win-amd64.egg\Crypto\Random\__init__.py", line 28, in <module>
    from Crypto.Random import OSRNG
  File "C:\Program Files\Python36\lib\site-packages\pycrypto-2.6.1-py3.6-win-amd64.egg\Crypto\Random\OSRNG\__init__.py", line 34, in <module>
    from Crypto.Random.OSRNG.nt import new
  File "C:\Program Files\Python36\lib\site-packages\pycrypto-2.6.1-py3.6-win-amd64.egg\Crypto\Random\OSRNG\nt.py", line 28, in <module>
    from . import winrandom
ImportError: DLL load failed: %1 is not a valid Win32 application.`

Any help is appreciated!

**Comment by bebound** [comment]
Something wrong with your `pycrypto` package.

If you can downgrade to py3.5, you can install `pycrypto` here:https://github.com/sfbahr/PyCrypto-Wheels
