### ISSUE TITLE
KeyError: 'access_token'

### ISSUE THREAD

**Issue by Legendsmith** [bebound/Pixiv#27]
This occurs when I try to login with a code, I'm sure I'm doing it right, copying the token after ``&code=``. I'm on windows 10 using powershell and python 3.9
```
Traceback (most recent call last):
  File "pixiv.py", line 380, in <module>
    sys.exit(main())
  File "pixiv.py", line 332, in main
    user = PixivApi()
  File "C:\Users\the-l\source\repos\pixiv\api.py", line 50, in __init__
    self.login_required()
  File "C:\Users\the-l\source\repos\pixiv\api.py", line 188, in login_required
    self.login()
  File "C:\Users\the-l\source\repos\pixiv\api.py", line 167, in login
    self.access_token, self.refresh_token = self.parse_token(r.json())
  File "C:\Users\the-l\source\repos\pixiv\api.py", line 114, in parse_token
    return data["access_token"], data["refresh_token"]
KeyError: 'access_token'
```

**Comment by bebound** [comment]
I can't reproduce it.
The only reason should be wrong code...
Make sure you find the url like `https://app-api.pixiv.net/web/v1/users/auth/pixiv/callback?state=R6uG778j3oGfZuVsTQfO6mc6Dx982NVlfVqH0psAdxxx&code=5u5xdHDOp3rvHHbfk3iOPgEPDe9ncTw9bcRAqXxxx` in network tab, and paste `5u5xdHDOp3rvHHbfk3iOPgEPDe9ncTw9bcRAqXxxx` as input.

----------------
If  it still does not work, add `print(data)` before `api.py` line 114 `return data["access_token"], data["refresh_token"]`, and give me the output. Thank you.
